-- Query definition corresponding to the source-count dataset in the portable
-- P11.5 report. The audited snapshot was generated by audit_dataset.py from
-- datasets/experiments/manifests/source_inventory.csv; no live SQL engine was
-- available or invoked during this run.
SELECT
    source_dataset AS source,
    COUNT(*) AS images
FROM source_inventory
WHERE source_path <> ''
GROUP BY source_dataset
ORDER BY images DESC;
