import { Camera, Target, Alert, Sighting, RouteResponse } from "../types/api";

export const DEMO_CAMERAS: Camera[] = [
  {
    camera_id: "cam_sg_highway_01",
    name: "SG Highway — ISCON Junction North",
    department: "Traffic Police — Division 1",
    latitude: 23.0298,
    longitude: 72.5067,
    azimuth: 15.0,
    location_quality: "VERIFIED",
    live: true,
    stream_status: "ONLINE",
    measured_fps: 29.8,
    last_checked: new Date().toISOString(),
    metadata: { junction: "ISCON Flyover", direction: "Northbound" },
  },
  {
    camera_id: "cam_sg_highway_02",
    name: "SG Highway — Pakwan Crossroad",
    department: "Traffic Police — Division 1",
    latitude: 23.0489,
    longitude: 72.5184,
    azimuth: 30.0,
    location_quality: "VERIFIED",
    live: true,
    stream_status: "ONLINE",
    measured_fps: 30.0,
    last_checked: new Date().toISOString(),
    metadata: { junction: "Pakwan", direction: "Northbound" },
  },
  {
    camera_id: "cam_ashram_rd_01",
    name: "Ashram Road — Income Tax Circle",
    department: "City Surveillance — Central",
    latitude: 23.0415,
    longitude: 72.5714,
    azimuth: 180.0,
    location_quality: "VERIFIED",
    live: true,
    stream_status: "ONLINE",
    measured_fps: 29.5,
    last_checked: new Date().toISOString(),
    metadata: { junction: "Income Tax Circle", direction: "Southbound" },
  },
  {
    camera_id: "cam_vastrapur_01",
    name: "Vastrapur Lake — West Entrance",
    department: "Traffic Police — Division 2",
    latitude: 23.0354,
    longitude: 72.5292,
    azimuth: 90.0,
    location_quality: "VERIFIED",
    live: true,
    stream_status: "ONLINE",
    measured_fps: 29.9,
    last_checked: new Date().toISOString(),
    metadata: { junction: "Vastrapur Roundabout" },
  },
  {
    camera_id: "cam_ring_road_01",
    name: "SP Ring Road — Vaishnodevi Circle",
    department: "Highway Patrol",
    latitude: 23.1189,
    longitude: 72.5401,
    azimuth: 45.0,
    location_quality: "VERIFIED",
    live: true,
    stream_status: "ONLINE",
    measured_fps: 30.0,
    last_checked: new Date().toISOString(),
    metadata: { junction: "Vaishnodevi Outer Ring" },
  },
  {
    camera_id: "cam_kalupur_01",
    name: "Kalupur Railway Station Plaza",
    department: "City Surveillance — East",
    latitude: 23.0232,
    longitude: 72.5998,
    azimuth: 270.0,
    location_quality: "VERIFIED",
    live: true,
    stream_status: "DEGRADED",
    measured_fps: 18.2,
    last_checked: new Date().toISOString(),
    metadata: { junction: "Station Main Gate", notes: "Sub-optimal FPS due to network congestion" },
  }
];

export const DEMO_TARGETS: Target[] = [
  {
    target_id: "tgt_demo_01",
    registration: "GJ01AB1234",
    normalized_registration: "GJ01AB1234",
    priority: "CRITICAL",
    enabled: true,
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    notes: "Suspect vehicle in commercial robbery case FIR-2026-881",
    metadata: { case_id: "FIR-2026-881", officer: "Insp. Verma" },
  },
  {
    target_id: "tgt_demo_02",
    registration: "GJ18XY5678",
    normalized_registration: "GJ18XY5678",
    priority: "HIGH",
    enabled: true,
    created_at: new Date(Date.now() - 3600000 * 12).toISOString(),
    notes: "Stolen black SUV reported missing from Gandhinagar sector 7",
    metadata: { case_id: "FIR-2026-742" },
  },
  {
    target_id: "tgt_demo_03",
    registration: "GJ05CD9999",
    normalized_registration: "GJ05CD9999",
    priority: "NORMAL",
    enabled: false,
    created_at: new Date(Date.now() - 3600000 * 48).toISOString(),
    notes: "Traffic violation repeat offender flagged for license suspension",
    metadata: { department: "RTO Enforcement" },
  }
];

export const DEMO_ALERTS: Alert[] = [
  {
    alert_id: "alt_demo_101",
    watchlist_id: "tgt_demo_01",
    sighting_id: "sight_demo_04",
    camera_id: "cam_sg_highway_02",
    stream_epoch: 1,
    track_id: 14,
    registration: "GJ01AB1234",
    match_score: 0.98,
    match_class: "EXACT",
    severity: "CRITICAL",
    created_at: new Date(Date.now() - 1000 * 90).toISOString(),
    acknowledged: false,
    explanation: [
      "Exact OCR match 'GJ01AB1234' with multi-frame consensus support = 3",
      "Observed on SG Highway Pakwan heading Northbound at 62 km/h",
      "High camera wallclock timing quality verified"
    ],
  },
  {
    alert_id: "alt_demo_102",
    watchlist_id: "tgt_demo_01",
    sighting_id: "sight_demo_03",
    camera_id: "cam_sg_highway_01",
    stream_epoch: 1,
    track_id: 9,
    registration: "GJ01AB1234",
    match_score: 0.96,
    match_class: "EXACT",
    severity: "CRITICAL",
    created_at: new Date(Date.now() - 1000 * 480).toISOString(),
    acknowledged: true,
    acknowledged_by: "ControlRoom_Operator_04",
    acknowledged_at: new Date(Date.now() - 1000 * 400).toISOString(),
    explanation: [
      "Multi-frame OCR consensus plate match confirmed",
      "Passage through ISCON Junction Northbound"
    ],
  }
];

export const DEMO_SIGHTINGS: Sighting[] = [
  {
    sighting_id: "sight_demo_01",
    camera_id: "cam_vastrapur_01",
    stream_epoch: 1,
    track_id: 3,
    first_pts_ms: 1000.0,
    last_pts_ms: 1800.0,
    registration_candidate: "GJ01AB1234",
    confidence: 0.92,
    match_score: 0.94,
    match_class: "HIGH_PROBABILITY",
    target_id: "tgt_demo_01",
    created_at: new Date(Date.now() - 1000 * 900).toISOString(),
    event_time_utc: new Date(Date.now() - 1000 * 900).toISOString(),
    event_time_source: "SOURCE_WALLCLOCK",
    event_time_quality: "HIGH",
  },
  {
    sighting_id: "sight_demo_02",
    camera_id: "cam_ashram_rd_01",
    stream_epoch: 1,
    track_id: 6,
    first_pts_ms: 2200.0,
    last_pts_ms: 3100.0,
    registration_candidate: "GJ01AB1234",
    confidence: 0.95,
    match_score: 0.95,
    match_class: "EXACT",
    target_id: "tgt_demo_01",
    created_at: new Date(Date.now() - 1000 * 680).toISOString(),
    event_time_utc: new Date(Date.now() - 1000 * 680).toISOString(),
    event_time_source: "SOURCE_WALLCLOCK",
    event_time_quality: "HIGH",
  },
  {
    sighting_id: "sight_demo_03",
    camera_id: "cam_sg_highway_01",
    stream_epoch: 1,
    track_id: 9,
    first_pts_ms: 4500.0,
    last_pts_ms: 5400.0,
    registration_candidate: "GJ01AB1234",
    confidence: 0.96,
    match_score: 0.96,
    match_class: "EXACT",
    target_id: "tgt_demo_01",
    created_at: new Date(Date.now() - 1000 * 480).toISOString(),
    event_time_utc: new Date(Date.now() - 1000 * 480).toISOString(),
    event_time_source: "PTS_ANCHORED_ESTIMATE",
    event_time_quality: "MEDIUM",
  },
  {
    sighting_id: "sight_demo_04",
    camera_id: "cam_sg_highway_02",
    stream_epoch: 1,
    track_id: 14,
    first_pts_ms: 8100.0,
    last_pts_ms: 9000.0,
    registration_candidate: "GJ01AB1234",
    confidence: 0.98,
    match_score: 0.98,
    match_class: "EXACT",
    target_id: "tgt_demo_01",
    created_at: new Date(Date.now() - 1000 * 90).toISOString(),
    event_time_utc: new Date(Date.now() - 1000 * 90).toISOString(),
    event_time_source: "SOURCE_WALLCLOCK",
    event_time_quality: "HIGH",
  }
];

export const DEMO_ROUTE_GJ01AB1234: RouteResponse = {
  target_id: "tgt_demo_01",
  registration: "GJ01AB1234",
  status: "PLAUSIBLE_SEQUENCE",
  trajectory_confidence: 0.94,
  start_time_utc: new Date(Date.now() - 1000 * 900).toISOString(),
  end_time_utc: new Date(Date.now() - 1000 * 90).toISOString(),
  duration_seconds: 810.0,
  total_lower_bound_distance_m: 8420.0,
  minimum_average_speed_kmh: 37.4,
  sighting_count: 4,
  camera_count: 4,
  sightings: [
    {
      sighting_id: "sight_demo_01",
      camera_id: "cam_vastrapur_01",
      event_time_utc: new Date(Date.now() - 1000 * 900).toISOString(),
      time_source: "SOURCE_WALLCLOCK",
      time_quality: "HIGH",
      latitude: 23.0354,
      longitude: 72.5292,
      location_quality: "VERIFIED",
      match_score: 0.94,
    },
    {
      sighting_id: "sight_demo_02",
      camera_id: "cam_ashram_rd_01",
      event_time_utc: new Date(Date.now() - 1000 * 680).toISOString(),
      time_source: "SOURCE_WALLCLOCK",
      time_quality: "HIGH",
      latitude: 23.0415,
      longitude: 72.5714,
      location_quality: "VERIFIED",
      match_score: 0.95,
    },
    {
      sighting_id: "sight_demo_03",
      camera_id: "cam_sg_highway_01",
      event_time_utc: new Date(Date.now() - 1000 * 480).toISOString(),
      time_source: "PTS_ANCHORED_ESTIMATE",
      time_quality: "MEDIUM",
      latitude: 23.0298,
      longitude: 72.5067,
      location_quality: "VERIFIED",
      match_score: 0.96,
    },
    {
      sighting_id: "sight_demo_04",
      camera_id: "cam_sg_highway_02",
      event_time_utc: new Date(Date.now() - 1000 * 90).toISOString(),
      time_source: "SOURCE_WALLCLOCK",
      time_quality: "HIGH",
      latitude: 23.0489,
      longitude: 72.5184,
      location_quality: "VERIFIED",
      match_score: 0.98,
    }
  ],
  segments: [
    {
      segment_id: "seg_01",
      sequence_index: 1,
      from_sighting_id: "sight_demo_01",
      to_sighting_id: "sight_demo_02",
      from_camera_id: "cam_vastrapur_01",
      to_camera_id: "cam_ashram_rd_01",
      distance_lower_bound_m: 4350.0,
      delta_seconds: 220.0,
      minimum_required_speed_kmh: 71.2,
      feasibility: "FEASIBLE",
      segment_score: 0.92,
      warnings: []
    },
    {
      segment_id: "seg_02",
      sequence_index: 2,
      from_sighting_id: "sight_demo_02",
      to_sighting_id: "sight_demo_03",
      from_camera_id: "cam_ashram_rd_01",
      to_camera_id: "cam_sg_highway_01",
      distance_lower_bound_m: 6720.0,
      delta_seconds: 200.0,
      minimum_required_speed_kmh: 121.0,
      feasibility: "QUESTIONABLE",
      segment_score: 0.78,
      warnings: ["High required transit speed (121 km/h) through urban corridor — likely highway bypass route."]
    },
    {
      segment_id: "seg_03",
      sequence_index: 3,
      from_sighting_id: "sight_demo_03",
      to_sighting_id: "sight_demo_04",
      from_camera_id: "cam_sg_highway_01",
      to_camera_id: "cam_sg_highway_02",
      distance_lower_bound_m: 2450.0,
      delta_seconds: 390.0,
      minimum_required_speed_kmh: 22.6,
      feasibility: "FEASIBLE",
      segment_score: 0.97,
      warnings: []
    }
  ],
  alternative_trajectories_count: 0,
  reasons: [
    "Chronological continuity verified across 4 CCTV camera sights",
    "All sightings exceed 0.94 match score threshold",
    "Consistent vehicle class across all observation nodes"
  ],
  warnings: [
    "Segment 2 exhibits QUESTIONABLE required velocity (121.0 km/h) under straight-line assumption",
    "Node 3 timestamp derived from PTS-anchored clock estimate"
  ],
  disclaimer: "LineString connects observed camera sightings in chronological order. It does NOT represent a reconstructed road-level polyline."
};
